### ISSUE TITLE
Items involving generic functions fail to return results depending on package scope. 

### ISSUE THREAD

**Issue by dmitsuki** [DanielGavin/ols#386]
Essentially title. When an item is returned from a generic function the ability for ols to parse it seems to change based on scope. 

main.odin

```odin
package main

import "testpackage"


CoolStruct :: struct
{
    val1, val2, val3: int,
}

main :: proc()
{
    testArray := make([dynamic]CoolStruct);
    otherTestArray := make([dynamic]testpackage.OtherStruct);

    //no completion on function or new value
    newValue := testpackage.DummyFunction(testArray, 10);
    newValue.val1 = 1;

    //Compleition works
    newerValue := testpackage.DummyFunction(otherTestArray, 10);
    newerValue.val1 = 10;
}

```
testpackage/testpackage.odin

```odin
package testpackage

OtherStruct :: struct 
{
    val1, val2, val3: int,
}

DummyFunction :: proc(value: $T/[dynamic]$E, index: int) -> ^E
{
    return &value[index]
}

```
[minirepo.zip](https://github.com/DanielGavin/ols/files/15278750/minirepo.zip)

**Comment by DanielGavin** [comment]
Should be fixed.

**Comment by dmitsuki** [comment]
It still fails on this case for me 

main.odin
```odin

package main

import "core:fmt"
import "testpackage"


CoolStruct :: struct
{
    val1, val2, val3: int,
}

main :: proc()
{
    //no completion on function or new value
    newValue := testpackage.DummyFunction(CoolStruct, CoolStruct{});
    newValue.val1 = 1;

    //Compleition works
    newerValue := testpackage.DummyFunction(testpackage.OtherStruct, testpackage.OtherStruct{});
    newerValue.val1 = 10;
    fmt.println("success");

}
```
testpackage/testpackage.odin

```odin
package testpackage

OtherStruct :: struct 
{
    val1, val2, val3: int,
}

DummyFunction :: proc($T: typeid, value: T) -> T
{
    return value;
}
```

**Comment by DanielGavin** [comment]
Try again.

**Comment by dmitsuki** [comment]
That seems to have fixed it, thanks!
