### ISSUE TITLE
foreign block inside a true when block isn't shown in autocomplete.

### ISSUE THREAD

**Issue by blob1807** [DanielGavin/ols#587]
Anything inside a foreign block inside a true when block isn't shown in autocomplete. I've not tested if it's an OLS or `core:odin` issue.
I've only tested this with VSCode & VSCodium. This isn't not a new issue, I've known about it for sometime.

This does come up in normal use. `vendor:stb/image` has `load` & `write_*` in a when block.

Copy the below. Neither `beans` nor `pies` will show up in autocomplete.
```odin
foreign import kern "system:some_import"

when true {
    foreign kern {
        beans :: proc() ---
        pies: i32
    }
}
```

**Comment by DanielGavin** [comment]
Should be fixed.

**Comment by blob1807** [comment]
Pulled & build the server from source. I'm still unable to get it to work.

**Comment by DanielGavin** [comment]
Try again.

**Comment by blob1807** [comment]
It's working now, thank you mate.
